# Generated by Django 6.0.3 on 2026-03-30 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bodegas',
            fields=[
                ('id_bodega', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_bodega', models.CharField(max_length=100)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('estado', models.CharField(blank=True, default='ACTIVA', max_length=8)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'bodegas',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id_categorias', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_categoria', models.CharField(max_length=300)),
                ('estado_categoria', models.CharField(blank=True, default='activo', max_length=45)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'categorias',
                'ordering': ['nombre_categoria'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('id_proveedor', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('estado', models.CharField(blank=True, default='ACTIVO', max_length=8)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'proveedores',
                'ordering': ['nombre'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_producto', models.CharField(max_length=45, unique=True)),
                ('referencia_producto', models.CharField(blank=True, max_length=100, null=True)),
                ('proveedor_id', models.PositiveIntegerField(blank=True, null=True)),
                ('tipo_madera', models.CharField(blank=True, max_length=45, null=True)),
                ('color_producto', models.CharField(blank=True, max_length=45, null=True)),
                ('precio_actual', models.DecimalField(decimal_places=2, max_digits=15)),
                ('estado', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('AGOTADO', 'Agotado')], default='DISPONIBLE', max_length=10)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('categoria', models.ForeignKey(db_column='categoria_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='productos', to='inventario.categorias')),
            ],
            options={
                'db_table': 'producto',
                'ordering': ['-created_at'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ImagenesProducto',
            fields=[
                ('id_imagen', models.AutoField(primary_key=True, serialize=False)),
                ('ruta_imagen', models.CharField(max_length=255)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('es_principal', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('producto', models.ForeignKey(db_column='producto_id', on_delete=django.db.models.deletion.DO_NOTHING, to='inventario.producto')),
            ],
            options={
                'db_table': 'imagenes_producto',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id_inventario', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_disponible', models.IntegerField(default=0)),
                ('cantidad_reservada', models.IntegerField(default=0, help_text='Cantidad reservada para pedidos pendientes')),
                ('fecha_llegada', models.DateField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('COMPROMETIDO', 'Comprometido'), ('AGOTADO', 'Agotado')], default='DISPONIBLE', max_length=12)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('bodega', models.ForeignKey(db_column='bodega_id', on_delete=django.db.models.deletion.PROTECT, related_name='inventarios', to='inventario.bodegas')),
                ('producto', models.ForeignKey(db_column='producto_id', on_delete=django.db.models.deletion.PROTECT, related_name='inventarios', to='inventario.producto')),
                ('proveedor', models.ForeignKey(blank=True, db_column='proveedor_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventarios', to='inventario.proveedores')),
            ],
            options={
                'db_table': 'inventario',
                'ordering': ['-fecha_registro'],
                'managed': True,
            },
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['codigo_producto'], name='producto_codigo__395862_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['estado'], name='producto_estado_a5740b_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['categoria'], name='producto_categor_b30d5c_idx'),
        ),
    ]
