# Generated by Django 6.0.6 on 2026-06-04 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagenesproducto',
            name='ruta_imagen',
            field=models.ImageField(blank=True, null=True, upload_to='productos/'),
        ),
    ]
