# Generated by Django 4.2 on 2026-05-18 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagostripe',
            name='monto',
            field=models.BigIntegerField(help_text='Monto en pesos COP — igual al amount enviado a Stripe (zero-decimal)'),
        ),
    ]
