# Generated by Django 6.0.6 on 2026-07-01 19:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0002_alter_pagostripe_monto'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagoWompi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencia', models.CharField(db_index=True, max_length=100, unique=True)),
                ('wompi_transaction_id', models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True)),
                ('payment_method_type', models.CharField(blank=True, max_length=30, null=True)),
                ('venta_id', models.IntegerField(blank=True, null=True)),
                ('pedido_id', models.IntegerField(blank=True, null=True)),
                ('cliente_id', models.IntegerField(blank=True, null=True)),
                ('monto', models.BigIntegerField(help_text='Monto en pesos COP (para mostrar en UI)')),
                ('monto_centavos', models.BigIntegerField(help_text='amount_in_cents — el valor real que maneja Wompi')),
                ('monto_reembolsado', models.BigIntegerField(default=0)),
                ('moneda', models.CharField(default='COP', max_length=3)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('COMPLETADO', 'Completado'), ('FALLIDO', 'Fallido'), ('CANCELADO', 'Cancelado'), ('REEMBOLSADO', 'Reembolsado')], db_index=True, default='PENDIENTE', max_length=12)),
                ('estado_wompi_raw', models.CharField(blank=True, help_text='Último status crudo de Wompi: APPROVED/DECLINED/ERROR/PENDING/VOIDED', max_length=20, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('metadata_json', models.TextField(blank=True, help_text='Última respuesta cruda de Wompi (auditoría)', null=True)),
                ('checkout_data_json', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, max_length=100, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'pagos_wompi',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='PagoStripe',
        ),
    ]
