# Generated by Django 4.2 on 2026-03-22 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carritos',
            fields=[
                ('id_carrito', models.AutoField(primary_key=True, serialize=False)),
                ('session_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'carritos',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_registro', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(blank=True, max_length=8, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'clientes',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Cotizaciones',
            fields=[
                ('id_cotizacion', models.AutoField(primary_key=True, serialize=False)),
                ('numero_cotizacion', models.CharField(max_length=255, unique=True)),
                ('venta_id', models.IntegerField(blank=True, null=True)),
                ('fecha_cotizacion', models.DateField(blank=True, null=True)),
                ('fecha_vencimiento', models.DateField()),
                ('estado', models.CharField(max_length=9)),
                ('tiempo_entrega', models.CharField(blank=True, max_length=255, null=True)),
                ('validez_dias', models.IntegerField(blank=True, null=True)),
                ('moneda', models.CharField(blank=True, max_length=10, null=True)),
                ('requiere_produccion', models.IntegerField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=15)),
                ('impuesto', models.DecimalField(decimal_places=2, max_digits=15)),
                ('descuento', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=15)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('consecutivo', models.IntegerField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ventas.clientes')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.usuarios')),
            ],
            options={
                'db_table': 'cotizaciones',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id_detalle', models.AutoField(primary_key=True, serialize=False)),
                ('pedido_id', models.IntegerField()),
                ('producto_id', models.IntegerField()),
                ('cantidad', models.IntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'detalle_pedido',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MetodosPago',
            fields=[
                ('id_metodo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'metodos_pago',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id_pedido', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_pedido', models.DateTimeField()),
                ('fecha_entrega_estimada', models.DateField(blank=True, null=True)),
                ('total_pedido', models.DecimalField(decimal_places=2, max_digits=15)),
                ('estado_pedido', models.CharField(max_length=10)),
                ('direccion_entrega', models.CharField(blank=True, max_length=255, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('numero_pedido', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('foto_orden', models.CharField(blank=True, max_length=255, null=True)),
                ('estado_facturacion', models.CharField(blank=True, max_length=12, null=True)),
                ('fecha_facturacion', models.DateTimeField(blank=True, null=True)),
                ('asesor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pedido_asesor_set', to='usuarios.usuarios')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ventas.clientes')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.usuarios')),
                ('usuario_facturo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pedido_usuario_facturo_set', to='usuarios.usuarios')),
            ],
            options={
                'db_table': 'pedido',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('id_venta', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_venta', models.CharField(max_length=12)),
                ('foto_orden', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_venta', models.DateTimeField()),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('impuesto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('descuento', models.DecimalField(decimal_places=2, max_digits=12)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('estado_venta', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('numero_factura', models.CharField(blank=True, max_length=50, null=True)),
                ('prefijo', models.CharField(blank=True, max_length=10, null=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ventas.clientes')),
                ('metodo_pago', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ventas.metodospago')),
                ('pedido', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ventas.pedido')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.usuarios')),
            ],
            options={
                'db_table': 'ventas',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ItemsCarrito',
            fields=[
                ('id_item', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=15)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('carrito', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='items', to='ventas.carritos')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventario.producto')),
            ],
            options={
                'db_table': 'items_carrito',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id_detalle', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('descuento', models.DecimalField(decimal_places=2, max_digits=12)),
                ('costo_estimado', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventario.producto')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ventas.ventas')),
            ],
            options={
                'db_table': 'detalle_venta',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DetalleCotizacion',
            fields=[
                ('id_detalle', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=15)),
                ('descuento', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=15)),
                ('costo_estimado', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ventas.cotizaciones')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventario.producto')),
            ],
            options={
                'db_table': 'detalle_cotizacion',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='carritos',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ventas.clientes'),
        ),
    ]
