# Generated by Django 6.0.3 on 2026-03-30 17:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetodosPago',
            fields=[
                ('id_metodo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'metodos_pago',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(blank=True, max_length=100, null=True)),
                ('documento', models.CharField(blank=True, max_length=50, null=True)),
                ('genero', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1, null=True)),
                ('contrasena_cliente', models.CharField(blank=True, max_length=255, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_registro', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(blank=True, choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo')], default='ACTIVO', max_length=8, null=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('ultimo_login', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'clientes',
                'ordering': ['apellido', 'nombre'],
                'managed': True,
                'indexes': [models.Index(fields=['email'], name='clientes_email_fb2cd6_idx'), models.Index(fields=['telefono'], name='clientes_telefon_4a8762_idx'), models.Index(fields=['documento'], name='clientes_documen_0d1be1_idx'), models.Index(fields=['estado'], name='clientes_estado_7dc145_idx')],
            },
        ),
        migrations.CreateModel(
            name='Carritos',
            fields=[
                ('id_carrito', models.AutoField(primary_key=True, serialize=False)),
                ('session_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ventas.clientes')),
            ],
            options={
                'db_table': 'carritos',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Cotizaciones',
            fields=[
                ('id_cotizacion', models.AutoField(primary_key=True, serialize=False)),
                ('numero_cotizacion', models.CharField(max_length=255, unique=True)),
                ('venta_id', models.IntegerField(blank=True, null=True)),
                ('fecha_cotizacion', models.DateField(blank=True, null=True)),
                ('fecha_vencimiento', models.DateField()),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('enviada', 'Enviada'), ('aceptada', 'Aceptada'), ('rechazada', 'Rechazada'), ('vencida', 'Vencida'), ('cancelada', 'Cancelada')], default='borrador', max_length=10)),
                ('tiempo_entrega', models.CharField(blank=True, max_length=255, null=True)),
                ('validez_dias', models.IntegerField(blank=True, default=30)),
                ('moneda', models.CharField(blank=True, default='COP', max_length=10)),
                ('requiere_produccion', models.IntegerField(default=False)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('impuesto', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('consecutivo', models.IntegerField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ventas.clientes')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.usuarios')),
            ],
            options={
                'db_table': 'cotizaciones',
                'ordering': ['-fecha_cotizacion', '-created_at'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DetalleCotizacion',
            fields=[
                ('id_detalle', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=15)),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=15)),
                ('costo_estimado', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ventas.cotizaciones')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventario.producto')),
            ],
            options={
                'db_table': 'detalle_cotizacion',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ItemsCarrito',
            fields=[
                ('id_item', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=15)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('carrito', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='items', to='ventas.carritos')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventario.producto')),
            ],
            options={
                'db_table': 'items_carrito',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id_pedido', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_pedido', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_entrega_estimada', models.DateField(blank=True, null=True)),
                ('total_pedido', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('estado_pedido', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CONFIRMADO', 'Confirmado'), ('EN PROCESO', 'En Proceso'), ('COMPLETADO', 'Completado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=10)),
                ('direccion_entrega', models.CharField(blank=True, max_length=255, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('numero_pedido', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('foto_orden', models.CharField(blank=True, max_length=255, null=True)),
                ('estado_facturacion', models.CharField(choices=[('NO_FACTURADO', 'No Facturado'), ('FACTURADO', 'Facturado')], default='NO_FACTURADO', max_length=12)),
                ('fecha_facturacion', models.DateTimeField(blank=True, null=True)),
                ('asesor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pedido_asesor_set', to='usuarios.usuarios')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ventas.clientes')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.usuarios')),
                ('usuario_facturo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pedido_usuario_facturo_set', to='usuarios.usuarios')),
            ],
            options={
                'db_table': 'pedido',
                'ordering': ['-fecha_pedido', '-created_at'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id_detalle', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventario.producto')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ventas.pedido')),
            ],
            options={
                'db_table': 'detalle_pedido',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('id_venta', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_venta', models.CharField(choices=[('DIRECTA', 'Venta Directa'), ('DESDE_PEDIDO', 'Desde Pedido'), ('DESDE_COTIZACION', 'Desde Cotización')], default='DIRECTA', max_length=20)),
                ('foto_orden', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_venta', models.DateTimeField()),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('impuesto', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('estado_venta', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('COMPLETADA', 'Completada'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=10)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('numero_factura', models.CharField(blank=True, max_length=50, null=True)),
                ('prefijo', models.CharField(blank=True, max_length=10, null=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ventas.clientes')),
                ('metodo_pago', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ventas.metodospago')),
                ('pedido', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ventas.pedido')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.usuarios')),
            ],
            options={
                'db_table': 'ventas',
                'ordering': ['-fecha_venta', '-created_at'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id_detalle', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('costo_estimado', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventario.producto')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ventas.ventas')),
            ],
            options={
                'db_table': 'detalle_venta',
                'managed': True,
            },
        ),
        migrations.AddIndex(
            model_name='cotizaciones',
            index=models.Index(fields=['numero_cotizacion'], name='cotizacione_numero__e967de_idx'),
        ),
        migrations.AddIndex(
            model_name='cotizaciones',
            index=models.Index(fields=['estado'], name='cotizacione_estado_6d68b2_idx'),
        ),
        migrations.AddIndex(
            model_name='cotizaciones',
            index=models.Index(fields=['cliente'], name='cotizacione_cliente_ef8f00_idx'),
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['numero_pedido'], name='pedido_numero__dc4441_idx'),
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['estado_pedido'], name='pedido_estado__d31605_idx'),
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['cliente'], name='pedido_cliente_7021c2_idx'),
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['estado_facturacion'], name='pedido_estado__08c540_idx'),
        ),
        migrations.AddIndex(
            model_name='ventas',
            index=models.Index(fields=['estado_venta'], name='ventas_estado__3087a5_idx'),
        ),
        migrations.AddIndex(
            model_name='ventas',
            index=models.Index(fields=['cliente'], name='ventas_cliente_b73e43_idx'),
        ),
        migrations.AddIndex(
            model_name='ventas',
            index=models.Index(fields=['fecha_venta'], name='ventas_fecha_v_df623b_idx'),
        ),
    ]
