# Generated by Django 6.0.3 on 2026-04-06 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_alter_cotizaciones_usuario_alter_pedido_usuario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='foto_perfil',
            field=models.ImageField(
                upload_to='avatars/',
                null=True,
                blank=True,
                default='avatars/default-avatar-1.png'
            ),
        ),
    ]
