# Generated by Django 6.0.3 on 2026-04-06 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0004_auto_20260406_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento'),
        ),
    ]
