# Generated by Django 4.2 on 2026-05-22 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0005_auto_20260406_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='email_verificado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clientes',
            name='token_reset_password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clientes',
            name='token_reset_password_expira',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientes',
            name='token_verificacion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clientes',
            name='token_verificacion_expira',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
