# Generated by Django 4.2.17 on 2026-06-10 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0006_clientes_email_verificado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransaccionWompi',
            fields=[
                ('id_transaccion', models.AutoField(primary_key=True, serialize=False)),
                ('wompi_transaction_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('referencia', models.CharField(max_length=100, unique=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('estado', models.CharField(choices=[('PENDING', 'Pendiente'), ('APPROVED', 'Aprobada'), ('DECLINED', 'Rechazada'), ('VOIDED', 'Anulada')], default='PENDING', max_length=20)),
                ('metodo_pago', models.CharField(blank=True, choices=[('CARD', 'Tarjeta de Crédito/Débito'), ('PSE', 'PSE'), ('NEQUI', 'Nequi'), ('TRANSFER', 'Transferencia')], max_length=20, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('respuesta_wompi', models.JSONField(blank=True, null=True)),
                ('es_sandbox', models.BooleanField(default=True)),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacciones_wompi', to='ventas.ventas')),
            ],
            options={
                'db_table': 'transacciones_wompi',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
