# Generated by Django 6.0.6 on 2026-06-23 19:19

import ventas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0007_transaccionwompi'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCombo',
            fields=[
                ('id_combo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('precio_original', models.DecimalField(decimal_places=2, max_digits=15)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=15)),
                ('ahorro', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('porcentaje_descuento', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('imagen_url', models.CharField(blank=True, max_length=500, null=True)),
                ('fecha_inicio', models.DateField(default=ventas.models.get_fecha_inicio_promocion)),
                ('fecha_fin', models.DateField(default=ventas.models.get_fecha_fin_promocion)),
                ('activa', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'promo_combo',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Promocion',
            fields=[
                ('id_promocion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('categoria', models.CharField(choices=[('sofas', 'Sofás'), ('camas', 'Camas'), ('escritorios', 'Escritorios'), ('comedores', 'Comedores'), ('sillas', 'Sillas'), ('nocheros', 'Nocheros'), ('mecedoras', 'Mecedoras'), ('general', 'General')], default='general', max_length=100)),
                ('precio_original', models.DecimalField(decimal_places=2, max_digits=15)),
                ('precio_promo', models.DecimalField(decimal_places=2, max_digits=15)),
                ('porcentaje_descuento', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('imagen_url', models.CharField(blank=True, max_length=500, null=True)),
                ('fecha_inicio', models.DateField(default=ventas.models.get_fecha_inicio_promocion)),
                ('fecha_fin', models.DateField(default=ventas.models.get_fecha_fin_promocion)),
                ('activa', models.BooleanField(default=True)),
                ('stock_disponible', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'promocion',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['categoria'], name='promocion_categor_ce6eb9_idx'), models.Index(fields=['activa'], name='promocion_activa_55cbbf_idx'), models.Index(fields=['fecha_inicio', 'fecha_fin'], name='promocion_fecha_i_daf929_idx')],
            },
        ),
    ]
