# Generated by Django 6.0.6 on 2026-06-23 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0008_promocombo_promocion'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenPromocion',
            fields=[
                ('id_imagen', models.AutoField(primary_key=True, serialize=False)),
                ('ruta_imagen', models.ImageField(upload_to='promociones/')),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('es_principal', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('promocion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='ventas.promocion')),
            ],
            options={
                'db_table': 'imagen_promocion',
                'ordering': ['-es_principal', 'created_at'],
            },
        ),
    ]
