# Generated by Django 6.0.6 on 2026-07-04 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0009_imagenpromocion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detalleventa',
            options={'managed': True, 'ordering': ['-created_at']},
        ),
        migrations.DeleteModel(
            name='TransaccionWompi',
        ),
    ]
