# Generated by Django 6.0.3 on 2026-03-30 17:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RolesOld',
            fields=[
                ('id_rol', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_rol', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'roles_old',
                'ordering': ['nombre_rol'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('documento', models.CharField(max_length=20, unique=True)),
                ('correo_usuario', models.CharField(max_length=255, unique=True)),
                ('contrasena_usuario', models.CharField(max_length=255)),
                ('genero', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo'), ('SUSPENDIDO', 'Suspendido')], default='ACTIVO', max_length=10)),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id_rol', models.ForeignKey(db_column='id_rol', on_delete=django.db.models.deletion.DO_NOTHING, related_name='usuarios', to='usuarios.rolesold')),
            ],
            options={
                'db_table': 'usuarios',
                'ordering': ['nombres'],
                'managed': True,
                'indexes': [models.Index(fields=['correo_usuario'], name='usuarios_correo__b44f85_idx'), models.Index(fields=['documento'], name='usuarios_documen_db8db0_idx'), models.Index(fields=['estado'], name='usuarios_estado_7877c9_idx')],
            },
        ),
    ]
