# Generated by Django 6.0.3 on 2026-04-06 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='foto_perfil',
            field=models.ImageField(blank=True, default='avatars/default-avatar-1.png', null=True, upload_to='avatars/'),
        ),
    ]
