"""
Django settings for orden_rae project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
import os
from pathlib import Path

# ==========================================
# CARGA DE VARIABLES DE ENTORNO (.env)
# ==========================================
from dotenv import load_dotenv
load_dotenv()  # Carga variables desde archivo .env

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY cargada desde variable de entorno (NUNCA hardcoded en producción)
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-cambia-esto-en-produccion')

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG controlado por variable de entorno
DEBUG = os.getenv('DEBUG', 'True') == 'True'

# ALLOWED_HOSTS desde variable de entorno (separados por coma)
ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')

EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    'django.contrib.humanize',
    # Nuestras Apps
    'dashboard',
    'usuarios',
    'inventario',
    'ventas',
    'compras',
    'produccion',
    'pagina',
    'reports',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware', # Middleware de seguridad para HTTPS, HSTS, etc.
    'django.contrib.sessions.middleware.SessionMiddleware', # Middleware para manejo de sesiones
    'usuarios.middleware.NoCacheMiddleware', # Middleware para evitar cache en páginas sensibles
    'django.middleware.common.CommonMiddleware',  # Middleware para manejo de URLs, redirecciones, etc.
    'django.middleware.csrf.CsrfViewMiddleware',  # Middleware para protección CSRF
    'django.contrib.auth.middleware.AuthenticationMiddleware', # Middleware de autenticación por defecto (Django)
    'ventas.middleware.ClientesAuthMiddleware',  # Clientes primero (prioridad máxima)
    'usuarios.middleware.CustomAuthMiddleware',   # Usuarios STAFF después (prioridad secundaria)
    'usuarios.middleware.SessionIdleTimeoutMiddleware',  # Middleware para timeout de sesión
    'django.contrib.messages.middleware.MessageMiddleware', # Middleware para mensajes flash
    'django.middleware.clickjacking.XFrameOptionsMiddleware', # Middleware para protección contra clickjacking
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'], 
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'ventas.context_processors.carrito_context',
                'usuarios.context_processors.user_permissions', 
                'django.template.context_processors.media', # Para usar MEDIA_URL en templates
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.getenv('DB_NAME', 'bd_orden_rae_django'),
        'USER': os.getenv('DB_USER', 'root'), 
        'PASSWORD': os.getenv('DB_PASSWORD', ''), 
        'HOST': os.getenv('DB_HOST', 'localhost'),
        'PORT': os.getenv('DB_PORT', '3306'),
        'OPTIONS': {
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
            'charset': 'utf8mb4', 
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'es-es'

TIME_ZONE = 'America/Bogota'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]

# Agrega esto para producción:
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Configuración para archivos multimedia (imágenes subidas por usuarios):
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Configuración para el sistema de mensajes
MESSAGE_STORAGE = 'django.contrib.messages.storage.session.SessionStorage'

# CONFIGURACIÓN DE AUTENTICACIÓN

LOGIN_URL = '/pagina/login/' # Redirige al login si no está autenticado (clientes → /pagina/login/, staff → /usuarios/login/)
LOGIN_REDIRECT_URL = 'dashboard:dashboard_home' # Redirige al dashboard después de login exitoso (ajusta según tu vista principal)
LOGOUT_REDIRECT_URL = '/pagina/login/' # Redirige al login después de logout
AUTHENTICATION_BACKENDS = [
    'usuarios.backends.UsuariosAuthBackend',  # Backend personalizado (PRIORITARIO)
    'ventas.backends.ClientesAuthBackend',  # Para clientes
    'django.contrib.auth.backends.ModelBackend',  # Backend por defecto (fallback)
]


# CONFIGURACIÓN DE TIMEOUT DE SESIÓN (10 MINUTOS)

# Tiempo de vida de la sesión para usuarios normales (10 minutos = 600 segundos)
SESSION_COOKIE_AGE = 86400 # 24 horas

# Tiempo de vida de la sesión para el admin (5 minutos = 300 segundos)
ADMIN_SESSION_TIMEOUT = 300  # 5 minutos

# Refrescar la cookie en cada solicitud para medir inactividad real
SESSION_SAVE_EVERY_REQUEST = True

# Expirar la sesión al cerrar el navegador (recomendado)
SESSION_EXPIRE_AT_BROWSER_CLOSE = False

# Usar la base de datos para almacenar sesiones (más seguro que cookies)
SESSION_ENGINE = 'django.contrib.sessions.backends.db'

# Cookies solo para HTTP (no accesibles desde JavaScript)
SESSION_COOKIE_HTTPONLY = True

# Cookies solo por HTTPS (activar cuando tengas SSL)
SESSION_COOKIE_SECURE = os.getenv('SECURE_SSL_REDIRECT', 'False') == 'True'

# Protección CSRF adicional contra ataques cross-site
SESSION_COOKIE_SAMESITE = 'Lax'


# CONFIGURACIÓN DE SEGURIDAD PARA PRODUCCIÓN

# --- HTTPS / SSL ---
# Redirigir todo tráfico HTTP a HTTPS (activar solo con certificado SSL instalado)
SECURE_SSL_REDIRECT = os.getenv('SECURE_SSL_REDIRECT', 'False') == 'True'

# HTTP Strict Transport Security (HSTS) - 1 año
SECURE_HSTS_SECONDS = 31536000
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD = True

# --- Cookies Seguras ---
# Enviar cookie CSRF solo por HTTPS
CSRF_COOKIE_SECURE = os.getenv('SECURE_SSL_REDIRECT', 'False') == 'True'
# Cookie CSRF no accesible desde JavaScript
CSRF_COOKIE_HTTPONLY = True
# Protección CSRF SameSite
CSRF_COOKIE_SAMESITE = 'Lax'

# --- Protección contra Clickjacking ---
# Prevenir que el sitio sea embebido en iframes
X_FRAME_OPTIONS = 'DENY'

# --- Protección contra MIME Sniffing ---
# Prevenir que el navegador interprete archivos con tipo MIME incorrecto
SECURE_CONTENT_TYPE_NOSNIFF = True

# --- Referrer Policy ---
# Controlar cuánta información del referer se envía
SECURE_REFERRER_POLICY = 'strict-origin-when-cross-origin'



# CONFIGURACIÓN DE EMAIL (Desarrollo vs Producción)

# Por defecto: consola (desarrollo)
EMAIL_BACKEND = os.getenv(
    'EMAIL_BACKEND', 
    'django.core.mail.backends.console.EmailBackend'
)

# Configuración SMTP para producción (se activa si EMAIL_BACKEND es smtp)
if 'smtp' in EMAIL_BACKEND:
    EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.gmail.com')
    EMAIL_PORT = int(os.getenv('EMAIL_PORT', 587))
    EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True') == 'True'
    EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')
    EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')
    DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'noreply@ordenrae.com')


# LOGGING PARA AUDITORÍA DE SEGURIDAD

# Crear carpeta logs si no existe
LOGS_DIR = os.path.join(BASE_DIR, 'logs')
os.makedirs(LOGS_DIR, exist_ok=True)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
        'security_file': {
            'level': 'WARNING',
            'class': 'logging.FileHandler',
            'filename': os.path.join(LOGS_DIR, 'security.log'),
            'formatter': 'verbose',
        },
        'django_file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': os.path.join(LOGS_DIR, 'django.log'),
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'django_file'],
            'level': 'INFO',
            'propagate': True,
        },
        'django.security': {
            'handlers': ['console', 'security_file'],
            'level': 'WARNING',
            'propagate': True,
        },
        'django.security.DisallowedHost': {
            'handlers': ['security_file'],
            'level': 'WARNING',
            'propagate': False,
        },
    },
}


# CONFIGURACIONES ADICIONALES

# Límite de tamaño para uploads (10 MB por defecto)
DATA_UPLOAD_MAX_MEMORY_SIZE = int(os.getenv('DATA_UPLOAD_MAX_MEMORY_SIZE', 10485760))  # 10 MB
FILE_UPLOAD_MAX_MEMORY_SIZE = int(os.getenv('FILE_UPLOAD_MAX_MEMORY_SIZE', 10485760))

# Protección contra CSRF en formularios (Django lo hace por defecto, pero es bueno explicitarlo)
CSRF_TRUSTED_ORIGINS = os.getenv('CSRF_TRUSTED_ORIGINS', 'http://localhost,http://127.0.0.1').split(',')

# Versión de la aplicación (útil para debugging y monitoreo)
APP_VERSION = os.getenv('APP_VERSION', '1.0.0')

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
    }
}