# Generated by Django 6.0.3 on 2026-03-30 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0001_initial'),
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produccion',
            fields=[
                ('id_produccion', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_producida', models.IntegerField()),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('estado_produccion', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN PROCESO', 'En Proceso'), ('TERMINADA', 'Terminada'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=15)),
                ('foto_orden', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventario.producto')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='inventario.proveedores')),
            ],
            options={
                'db_table': 'produccion',
                'ordering': ['-fecha_inicio', '-created_at'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DetalleProduccionPedido',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cantidad_asignada', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ventas.pedido')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventario.producto')),
                ('produccion', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='produccion.produccion')),
            ],
            options={
                'db_table': 'detalle_produccion_pedido',
                'managed': True,
                'unique_together': {('produccion', 'pedido', 'producto')},
            },
        ),
    ]
