# Generated by Django 4.2 on 2026-03-15 16:52

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='categorias/')),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Categorías',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Testimonio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cliente', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('comentario', models.TextField()),
                ('estrellas', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('aprobado', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('descripcion', models.TextField()),
                ('descripcion_corta', models.CharField(blank=True, max_length=300)),
                ('precio', models.DecimalField(decimal_places=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('precio_original', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('imagen_principal', models.ImageField(upload_to='productos/')),
                ('imagenes_adicionales', models.JSONField(blank=True, default=list, help_text='Lista de URLs de imágenes adicionales')),
                ('stock', models.PositiveIntegerField(default=0)),
                ('tiene_opciones', models.BooleanField(default=False, help_text='¿El producto tiene variantes como color, tamaño?')),
                ('opciones', models.JSONField(blank=True, default=list, help_text='Lista de opciones disponibles')),
                ('activo', models.BooleanField(default=True)),
                ('nuevo', models.BooleanField(default=False, help_text="Mostrar en sección 'Nuevos Productos'")),
                ('destacado', models.BooleanField(default=False, help_text='Mostrar en slider principal')),
                ('en_oferta', models.BooleanField(default=False)),
                ('visitas', models.PositiveIntegerField(default=0)),
                ('ventas', models.PositiveIntegerField(default=0)),
                ('calificacion_promedio', models.DecimalField(decimal_places=2, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('reseñas_count', models.PositiveIntegerField(default=0)),
                ('meta_titulo', models.CharField(blank=True, max_length=200)),
                ('meta_descripcion', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('fecha_disponible', models.DateTimeField(blank=True, null=True)),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='pagina.categoria')),
            ],
            options={
                'ordering': ['-fecha_creacion', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('mensaje', models.TextField()),
                ('tipo', models.CharField(choices=[('carrito', '🛒 Carrito'), ('pedido', '📦 Pedido'), ('promocion', '🎁 Promoción'), ('sistema', '⚙️ Sistema')], default='sistema', max_length=20)),
                ('leida', models.BooleanField(default=False)),
                ('url', models.URLField(blank=True, help_text='URL opcional para redirigir al hacer clic')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['slug'], name='pagina_prod_slug_3d7ec6_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['activo', 'nuevo'], name='pagina_prod_activo_7893ae_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['categoria', 'activo'], name='pagina_prod_categor_8540b4_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['destacado', 'activo'], name='pagina_prod_destaca_a2943b_idx'),
        ),
    ]
