# Generated by Django 6.0.3 on 2026-03-30 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0001_initial'),
        ('usuarios', '0001_initial'),
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compras',
            fields=[
                ('id_compra', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_compra', models.DateField()),
                ('total_compra', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('estado', models.CharField(blank=True, choices=[('PENDIENTE', 'Pendiente'), ('RECIBIDA', 'Recibida'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=10, null=True)),
                ('foto_orden', models.CharField(blank=True, max_length=255, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventario.proveedores')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.usuarios')),
            ],
            options={
                'db_table': 'compras',
                'ordering': ['-fecha_compra', '-created_at'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DetalleCompra',
            fields=[
                ('id_detalle_compra', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=15)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=15)),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='compras.compras')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventario.producto')),
            ],
            options={
                'db_table': 'detalle_compra',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DetalleCompraPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_asignada', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='compras.compras')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ventas.pedido')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventario.producto')),
            ],
            options={
                'db_table': 'detalle_compra_pedido',
                'managed': True,
            },
        ),
        migrations.AddIndex(
            model_name='compras',
            index=models.Index(fields=['estado'], name='compras_estado_9eba4f_idx'),
        ),
        migrations.AddIndex(
            model_name='compras',
            index=models.Index(fields=['proveedor'], name='compras_proveed_c6e737_idx'),
        ),
        migrations.AddIndex(
            model_name='compras',
            index=models.Index(fields=['fecha_compra'], name='compras_fecha_c_e951e7_idx'),
        ),
        migrations.AddIndex(
            model_name='detallecompra',
            index=models.Index(fields=['compra'], name='detalle_com_compra__b38625_idx'),
        ),
        migrations.AddIndex(
            model_name='detallecompra',
            index=models.Index(fields=['producto'], name='detalle_com_product_731a48_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='detallecomprapedido',
            unique_together={('compra', 'pedido', 'producto')},
        ),
    ]
